/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.69
 * Generated at: 2017-07-13 09:04:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import cn.jbit.mybatisdemo.entity.Emp;
import java.util.List;

public final class EmpList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	List<Emp> list = (List<Emp>)request.getAttribute("empList");

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>员工列表</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css\" integrity=\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"http://www.jeasyui.net/Public/js/easyui/themes/default/easyui.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"col-md-8 col-md-offset-2\">\r\n");
      out.write("<table class=\"table table-hover table-striped\">\r\n");
      out.write("\t<caption class=\"h1 text-center\">员工列表<small>（总员工数：");
      out.print(list.size() );
      out.write("）</small></caption>\r\n");
      out.write("\t<thead>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"10\" class=\"bg-success\">\r\n");
      out.write("\t\t\t\t<form class=\"form-inline\" method=\"get\">\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/AddEmp\" class=\"btn btn-success\">添加员工</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"pull-right\">\r\n");
      out.write("\t\t\t\t\t\t<select class=\"easyui-combobox\">\r\n");
      out.write("\t\t\t\t\t\t");

							for(Emp emp:list){
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"");
      out.print(emp.getEmpno() );
      out.write('"');
      out.write('>');
      out.print(emp.getEmpno() );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"empno\" class=\"form-control\" placeholder=\"员工编号\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"empname\" class=\"form-control\" placeholder=\"员工姓名\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"查询\" class=\"btn btn-primary\"/>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>#</th><th>员工编号</th><th>员工姓名</th><th>入职时间</th><th>员工职位</th><th>员工工资</th><th>经理编号</th><th>奖金</th><th>部门编号</th>\r\n");
      out.write("\t\t\t<th>操作</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</thead>\r\n");
      out.write("\t<tbody>\r\n");
      out.write("\t\t");

			for(int i = 0; i < list.size(); i++){
				Emp emp = list.get(i);
		
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>");
      out.print(i+1 );
      out.write("</th>\r\n");
      out.write("\t\t\t<td>");
      out.print(emp.getEmpno() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(emp.getEmpname() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");

			if(emp.getHireDate()!=null){
				SimpleDateFormat sdf = new SimpleDateFormat("YYYY-MM-dd");
				out.print(sdf.format(emp.getHireDate()));
			}
			
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(emp.getJob() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(emp.getSalary() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(emp.getMgr() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(emp.getComm()==null?0:emp.getComm() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print(emp.getDeptNo() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<a class=\"btn btn-info glyphicon glyphicon-edit\" href=\"");
      out.print(request.getContextPath() );
      out.write("/UpdateEmp?empno=");
      out.print(emp.getEmpno() );
      out.write("\"> 修改</a>\r\n");
      out.write("\t\t\t\t<a class=\"btn btn-danger glyphicon glyphicon-trash\" href=\"");
      out.print(request.getContextPath() );
      out.write("/DeleteEmp?empno=");
      out.print(emp.getEmpno() );
      out.write("\" onclick=\"return confirm('确认要删除吗？');\"> 删除</a>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\t</tbody>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://www.jeasyui.net/Public/js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://www.jeasyui.net/Public/js/easyui/jquery.easyui.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
